name: Backport merged pull request
on:
  pull_request_target:
    # Run on merge (close) or if label is added after merging
    types: [closed, labeled]
jobs:
  backport:
    permissions:
      contents: write # so it can comment
      pull-requests: write # so it can create pull requests
    name: Backport pull request
    runs-on: ubuntu-latest
    # Don't run on closed unmerged pull requests
    if: github.event.pull_request.merged
    # Save the output from the create-pr step so it can be used in downstream jobs
    # https://github.com/korthout/backport-action/blob/e53c7b292aa9985d372c178a89d416ef2176c091/README.md#outputs
    outputs:
      was_successful: ${{ steps.create-pr.outputs.was_successful }}
    steps:
      - uses: actions/checkout@v4
      - id: create-pr
        name: Create backport pull requests
        uses: korthout/backport-action@v2
        with:
          github_token: ${{ secrets.BACKPORT_TOKEN }}
  open-issue:
    permissions:
      contents: read
      issues: write
    name: Open issue for failed backports
    runs-on: ubuntu-latest
    needs: backport
    # Open an issue only if the backport job failed
    if: ${{ needs.backport.outputs.was_successful == 'false' }}
    steps:
      - uses: actions/checkout@v4
      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        with:
          filename: .github/templates/failed-backport-issue.md
