name: Publish docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          name: fedimint
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        continue-on-error: true

      - name: Build docs
        run: nix build -L .#debug.workspaceDocExport

      - if: github.repository == 'fedimint/fedimint'
        name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/
          cname: docs.fedimint.org
